/**
 * Executive brief reader (C4, docs/pilot-launch-plan.md).
 *
 * Every statement renders with its epistemic kind — fact, calculation,
 * interpretation, recommendation — visually distinguished, because the brief
 * exists to keep those separate. Until this page existed, briefs were
 * write-only: generated, gated, stored, and unreadable.
 */
import { PageHeader, PageShell } from "@/components/layout/page";
import Link from "next/link";
import { notFound } from "next/navigation";
import { getExecutiveBrief } from "@/db/control-tower";
import { Badge } from "@/components/ui/badge";

export const dynamic = "force-dynamic";

const KIND_VARIANT: Record<string, "default" | "secondary" | "outline" | "destructive"> = {
  fact: "default",
  calculation: "secondary",
  recommendation: "outline",
  interpretation: "outline",
  correlation: "outline",
  causal: "destructive",
};

export default async function BriefPage({
  params,
}: {
  params: Promise<{ briefId: string }>;
}) {
  const { briefId } = await params;
  const brief = await getExecutiveBrief(briefId);
  if (!brief) notFound();

  const statements = brief.sections.statements ?? [];
  const risks = brief.sections.risks ?? [];
  const uncertainties = brief.sections.uncertainties ?? [];

  return (
    <PageShell>
      <PageHeader
        crumbs={[{ label: "Control tower", href: "/control-tower" }, { label: "Brief" }]}
        title={brief.sections.headline ?? `${brief.projectName} — ${brief.kind} brief`}
        description={
          <>
            {brief.kind} · {brief.periodStart.toISOString().slice(0, 10)} →{" "}
            {brief.periodEnd.toISOString().slice(0, 10)} · generated by{" "}
            {brief.generatedBy} · {brief.evidenceIds.length} evidence id(s) ·{" "}
            <Link
              href={`/projects/${brief.projectId}`}
              className="underline-offset-2 hover:underline"
            >
              {brief.projectName}
            </Link>
          </>
        }
      />

      {statements.length === 0 ? (
        <div className="rounded-lg border border-dashed p-8 text-center text-sm text-muted-foreground">
          A quiet period — nothing crossed the materiality threshold and no
          work items changed.
        </div>
      ) : (
        <ul className="space-y-2">
          {statements.map((statement, index) => (
            <li key={index} className="flex items-start gap-2 text-sm">
              <Badge
                variant={KIND_VARIANT[statement.kind] ?? "outline"}
                className="mt-0.5 shrink-0 text-[10px]"
              >
                {statement.kind}
              </Badge>
              <span>
                {statement.text}
                {statement.material && (
                  <span className="ml-2 text-xs text-muted-foreground">
                    · material · {statement.evidenceIds.length} evidence id(s)
                  </span>
                )}
              </span>
            </li>
          ))}
        </ul>
      )}

      {risks.length > 0 && (
        <section className="mt-8">
          <h2 className="mb-2 text-lg font-medium">Risks</h2>
          <ul className="list-disc space-y-1 pl-5 text-sm">
            {risks.map((risk, index) => (
              <li key={index}>{risk}</li>
            ))}
          </ul>
        </section>
      )}

      {uncertainties.length > 0 && (
        <section className="mt-6">
          <h2 className="mb-2 text-lg font-medium">Uncertainty</h2>
          <ul className="list-disc space-y-1 pl-5 text-sm text-muted-foreground">
            {uncertainties.map((uncertainty, index) => (
              <li key={index}>{uncertainty}</li>
            ))}
          </ul>
        </section>
      )}
    </PageShell>
  );
}
